### ISSUE TITLE
Continuous Mode

### ISSUE THREAD

**Issue by tricktux** [metent/uair#1]
1. Thanks for a great tool
  - I was close to writing something like this myself until I found it
2. The only quick is that this is how my config looks like:

```yaml

[defaults]
format = "{time}\n"
autostart = false

[[sessions]]
name = "Work"
duration = "25m"
format = "\U0001F345{time} \n"
command = "notify-send 'Pomodoro' 'Work Done!'"

[[sessions]]
name = "Rest"
duration = "5m"
format = "\U0001F3D6 {time}end \n"
command = "notify-send 'Pomodoro' 'Rest Done!'"

[[sessions]]
name = "Work"
duration = "25m"
format = "\U0001F345{time} \n"
command = "notify-send 'Pomodoro' 'Work Done!'"

[[sessions]]
name = "Rest"
duration = "5m"
format = "\U0001F3D6 {time}end \n"
command = "notify-send 'Pomodoro' 'Rest Done!'"

[[sessions]]
name = "Work"
duration = "25m"
format = "\U0001F345{time} \n"
command = "notify-send 'Pomodoro' 'Work Done!'"

[[sessions]]
name = "Rest"
duration = "5m"
format = "\U0001F3D6 {time}end \n"
command = "notify-send 'Pomodoro' 'Rest Done!'"

[[sessions]]
name = "Work"
duration = "25m"
format = "\U0001F345{time} \n"
command = "notify-send 'Pomodoro' 'Work Done!'"

[[sessions]]
name = "Rest"
duration = "5m"
format = "\U0001F3D6 {time}end \n"
command = "notify-send 'Pomodoro' 'Rest Done!'"

[[sessions]]
name = "Work"
duration = "25m"
format = "\U0001F345{time} \n"
command = "notify-send 'Pomodoro' 'Work Done!'"

[[sessions]]
name = "Rest"
duration = "5m"
format = "\U0001F3D6 {time}end \n"
command = "notify-send 'Pomodoro' 'Rest Done!'"

[[sessions]]
name = "Work"
duration = "25m"
format = "\U0001F345{time} \n"
command = "notify-send 'Pomodoro' 'Work Done!'"

[[sessions]]
name = "Rest"
duration = "5m"
format = "\U0001F3D6 {time}end \n"
command = "notify-send 'Pomodoro' 'Rest Done!'"

[[sessions]]
name = "Work"
duration = "25m"
format = "\U0001F345{time} \n"
command = "notify-send 'Pomodoro' 'Work Done!'"

[[sessions]]
name = "Rest"
duration = "5m"
format = "\U0001F3D6 {time}end \n"
command = "notify-send 'Pomodoro' 'Rest Done!'"

```

My normal flow is to do a Pomodoro of X length, break of Y length, rinse and repeat

The app does not provide a straight forward way to configure this right now other than having a 87 line config file

Typically Pomodoro apps have settings like these:

```
pomodoro_time_work = 25
pomodoro_time_slack = 5
# This is like every 4 pomos for example take a longer break
pomodoros_before_reward = 4
pomodoro_time_reward = 25

```

Which the above config could be implemented in the `yaml` config, but I would argue that a 6 line config is more idiomatic than an 87 one

**Comment by metent** [comment]
Thanks for using uair! It makes me happy knowing people use my software. There is a global variable named `loop_on_end` (see man page), which you can set to `true` to endlessly loop the sessions mentioned in the sessions array, which is not what you want exactly, but you can use it to keep your config file shorter. Looping for a said amount of times is currently unimplemented, but seems extremely trivial to implement. I'll implement it after I'm done with this semester's exams (soon-ish)
`uair` was written to be extremely customizable, which is why it lets you 'write' your own sessions instead of having only alternating 'Work' and 'Rest' sessions. However, it results in lengthy configuration files in case of complex configurations. An example can be a one long rest session after four alternative work and rest sessions. This is something I wish to resolve, and this problem will be eventually approached while keeping configuration flexibility in mind.

**Comment by tricktux** [comment]
The `loop_on_end` was exactly what I was looking for. My bad for not reading the man pages more thoroughly.

Excellent piece of software for a student. Very complete, even with man pages. Keep it up!

Good luck in your finals 💪🏻
