### ISSUE TITLE
nom8 is EOL

### ISSUE THREAD

**Issue by epage** [metent/uair#9]
As a heads up, nom8 was an experimental, short-lived fork for ideas I was trying out for nom v8.

Options
- Keep on using it
- Switch to nom v7
- Wait for the official, upcoming nom v8 which includes some of the ideas from nom8
- Switch to my long-term fork, `winnow` ([announcement](https://epage.github.io/blog/2023/02/winnow-toml-edit-combine-nom/))

**Comment by metent** [comment]
Hi, Thanks for the heads up! `uair` currently depends on `nom8` instead of regular nom crate to avoid linking two versions of nom. Since using `toml` brings up `nom8` as a dependency anyway, I decided to go with `nom8` for the parsing. I'll switch to using `winnow` as soon as `toml` (indirectly) depends on `winnow`.

**Comment by epage** [comment]
With a `cargo update` you should get the latest `toml_edit` which should upgrade you to winnow.

**Comment by metent** [comment]
> With a cargo update you should get the latest toml_edit which should upgrade you to winnow.

It does. I didn't know that cargo doesn't automatically update indirect dependencies on cargo build/run. Thanks.
